### PR TITLE
Support navgiation between pages on the same domain by keeping events in...

### PR DESCRIPTION
**Pull request by jasdeepgosal**
... sessionStorage.

https://github.com/facebook/huxley/issues/10

This isn't perfect, but it's an attempt at implementing the solution described in the comments on that issue.

### CODE REVIEW

**Comment by robfe11** [comment]
Thanks for that, haven't had a chance to test it out yet, does it work for all cases?

**Comment by petehunt** [comment]
@mrdeep thanks for doing this!

I am a little concerned about using a timer though. I believe that it will be possible to have a race condition such that we miss some events and it's confusing to the end-user since we have no way of detecting the error. Would you be opposed to, at least initially, modifying this to not use a timer and instead require a console message (i.e. type "i" to re-inject the JS)? I think eventually we may want to go with the timer, but I would rather make things explicit and move forward rather than starting with them implicit and having to backpedal later.

**Comment by javed-atp** [comment]
Hi,

I want to use Huxley for crossbrowser testing. In our application we need to navigate to different pages on the same domain. 

Successfully installed the huxley, currently facing the problem while recording - getting the below error

TestError: Could not call window._getHuxleyEvents(). This usually means you navi
gated to a new page, which is currently unsupported.

I have tried the solution described in the above comment, it is not working. 

Could any one please suggest how to proceed...

Thanks

**Comment by jessicard** [comment]
I noticed this hasn't been touched in awhile but the support would be really awesome - any plans on finishing this/merging this in for https://github.com/facebook/huxley/issues/10?

**Pull request closed without merging**
