### PR TITLE
fix(gitignore) : Ignore some files

### PR DESCRIPTION
**Pull request by sriram-mv**
Trivial fix on git ignore.

### CODE REVIEW

**Comment by petehunt** [comment]
Thanks for the contribution! Can you please sign the CLA and let me know when you've done it? Thanks! https://developers.facebook.com/opensource/cla

**Comment by sriram-mv** [comment]
Signed CLA. Thanks!

**Comment by petehunt** [comment]
Hey there, if you can rebase I can merge this in!

**Comment by petehunt** [comment]
It looks like there's a lot of extra changes in this, can you rebase?

**Pull request closed without merging**
