### PR TITLE
Modified retrieval of version info to fix install issue.

### PR DESCRIPTION
**Pull request by emanlove**
If you try to install huxley within a clean environment, like virtualenv,
then setup tries to import huxley to get version information before the
dependencies are install.  This puts setup into a catch-22 as importing
huxley also tries to input uninstalled dependencies.

Sample test code to verify issue and fix ...

```
$ mkdir install-huxley-test
$ cd install-huxley-test

~/install-huxley-test $ git clone git@github.com:emanlove/huxley.git emanlove
```

First revert my fix to show issue

```
~/install-huxley-test $ cd emanlove
~/install-huxley-test/emanlove $ git checkout HEAD^ setup.py
~/install-huxley-test/emanlove $ cd ..

~/install-huxley-test $ virtualenv -p /usr/bin/python2.6 --no-site-packages clean-python-env
~/install-huxley-test $ source ~/clean-python-env/bin/activate
(clean-python-env) ~/install-huxley-test $ cd emanlove
(clean-python-env) ~/install-huxley-test/emanlove $ python setup.py install

(clean-python-env) ~/install-huxley-test/emanlove $ deactivate
```

Reapply my fix and regenerate clean virtualenv

```
~/install-huxley-test/emanlove $ git checkout HEAD setup.py
~/install-huxley-test/emanlove $ cd ..

~/install-huxley-test $ virtualenv -p /usr/bin/python2.6 --no-site-packages clean-python-env
~/install-huxley-test $ source ~/clean-python-env/bin/activate
(clean-python-env) ~/install-huxley-test $ cd emanlove
(clean-python-env) ~/install-huxley-test/emanlove $ python setup.py install
```

Note I am working on signing CLA via directly signing the Word document as I don't have a FB account.

### CODE REVIEW

**Comment by emanlove** [comment]
Note this applies to issue #1

**Comment by petehunt** [comment]
Cool, I can't actually merge this until I've confirmed that you've signed the CLA :/ sorry. However that's pretty lame that you need an FB account to sign the CLA, I'll bring that up with our open-source folks today. Comment here when you manage to use the Word version, if you're stuck we can figure something else out.

**Comment by scottmac** [comment]
It was a design decision made 3 years ago to help prevent spam and basically ease of use. We have a paper version of the CLA and @jamesgpearce is working on removing the Facebook account requirement.

**Comment by emanlove** [comment]
Signed CLA on it's (electronic) way.

**Comment by petehunt** [comment]
Thanks!

**Pull request merged**
